spring:
  application:
    name: crypto-aggregator-be
  config:
    import:
      - 'classpath:exchanges.yaml'
      - 'optional:file:.env'
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crypto_aggregator_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations:
      - 'classpath:/db/migration/schema'
      - 'classpath:/db/migration/data'

security:
  jwt:
    secret-key: ${SECRET_TOKEN:519265gRvMBWa8iSB8Qj0Za1pZM998WiGELw9L8y56yitcTLOFaEjqrJTGKbYMxr}
    access-token-expiration: ${ACCESS_TOKEN:3600000}
    refresh-token-expiration: ${REFRESH_TOKEN:604800000}
