spring:
  application:
    name: crypto-aggregator-be
  config:
    import: classpath:exchanges.yaml
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crypto_aggregator_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations:
      - 'classpath:/db/migration/schema'
      - 'classpath:/db/migration/data'
