services:
  postgres:
    image: postgres:16-alpine
    container_name: crypto-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_aggregator_db
    volumes:
      - postgres_data:/var/lib/postgres/data

  redis:
    image: redis:7.2-alpine
    container_name: crypto-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru

volumes:
  postgres_data:
  redis_data: